## Q1: Questions on Basic NumPy Array

In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
reversed_arr = np.flip(arr)

print("Original array:", arr)
print("Reversed array:", reversed_arr)

Original array: [1 2 3 4 5]
Reversed array: [5 4 3 2 1]


In [ ]:
arr1=np.array([7,8,9])
arr1=arr1[::-1]
arr1

array([9, 8, 7])

In [ ]:
array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])


flattened_array1 = array1.flatten()


flattened_array2 = array1.ravel()

print("Original array:\n", array1)
print("Flattened array (flatten()):\n", flattened_array1)
print("Flattened array (ravel()):\n", flattened_array2)

Original array:
 [[1 2 3]
 [2 4 5]
 [1 2 3]]
Flattened array (flatten()):
 [1 2 3 2 4 5 1 2 3]
Flattened array (ravel()):
 [1 2 3 2 4 5 1 2 3]


In [ ]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])

# Check if the arrays are equal
if np.array_equal(arr1, arr2):
    print("The arrays are equal.")
else:
    print("The arrays are not equal.")

# Check if the arrays are identical (same object)
if arr1 is arr2:
    print("The arrays are identical (same object).")
else:
    print("The arrays are not identical (different objects).")

The arrays are equal.
The arrays are not identical (different objects).


In [ ]:
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])

# Find unique values and their counts
unique_y, counts_y = np.unique(y, return_counts=True)

# Find the index of the maximum count
max_count_index_y = np.argmax(counts_y)


# Most frequent value
most_frequent_value_y = unique_y[max_count_index_y]
# Indices of the most frequent value
indices_y = np.where(y == most_frequent_value_y)[0]

print(f"Array y: {y}")
print(f"Most frequent value in y: {most_frequent_value_y}")
print(f"Indices of the most frequent value in y: {indices_y}")

0
Array y: [1 1 1 2 3 4 2 4 3 3]
Most frequent value in y: 1
Indices of the most frequent value in y: [0 1 2]


In [ ]:

gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')

# i. Sum of all elements
total_sum = np.sum(gfg)

# ii. Sum of all elements row-wise
row_sum = np.sum(gfg, axis=1)

# iii. Sum of all elements column-wise
column_sum = np.sum(gfg, axis=0)

# Output results
print("Sum of all elements:", total_sum)
print("Sum of all elements row-wise:", row_sum)
print("Sum of all elements column-wise:", column_sum)

Sum of all elements: 45
Sum of all elements row-wise: [[14]
 [16]
 [15]]
Sum of all elements column-wise: [[20  9 16]]


In [ ]:

n_array = np.array([[55, 25, 15],
                    [30, 44, 2],
                    [11, 45, 77]])

# i. Sum of diagonal elements
diagonal_sum = np.trace(n_array)

# ii. Eigenvalues of the matrix
eigenvalues = np.linalg.eigvals(n_array)

# iii. Eigenvectors of the matrix
eigenvalues_full, eigenvectors = np.linalg.eig(n_array)

# iv. Inverse of the matrix
inverse_matrix = np.linalg.inv(n_array)

# v. Determinant of the matrix
determinant = np.linalg.det(n_array)

# Output results
print("Sum of diagonal elements:", diagonal_sum)
print("Eigenvalues of the matrix:", eigenvalues)
print("Eigenvectors of the matrix:\n", eigenvectors)
print("Inverse of the matrix:\n", inverse_matrix)
print("Determinant of the matrix:", determinant)

Sum of diagonal elements: 176
Eigenvalues of the matrix: [98.16835147 28.097044   49.73460452]
Eigenvectors of the matrix:
 [[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
Inverse of the matrix:
 [[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
Determinant of the matrix: 137180.0000000001


In [ ]:
p = np.array([[1, 2],
              [2, 3],
              [4, 5]])

q = np.array([[4, 5, 1],
              [6, 7, 2]])

result = np.dot(p, q)

print("Matrix Multiplication Result:")
print(result)

cov_matrix = np.cov([p.flatten(), q.flatten()])

print("Covariance Matrix:")
print(cov_matrix)



p1 = np.array([[1, 2], [2, 3], [4, 5]])
q1 = np.array([[4, 5, 1], [6, 7, 2]])

result1 = np.dot(p1, q1)

print("Matrix Multiplication Result:")
print(result1)

cov_matrix1 = np.cov([p1.flatten(), q1.T.flatten()])

print("Covariance Matrix:")
print(cov_matrix1)






Matrix Multiplication Result:
[[16 19  5]
 [26 31  8]
 [46 55 14]]
Covariance Matrix:
[[2.16666667 0.23333333]
 [0.23333333 5.36666667]]
Matrix Multiplication Result:
[[16 19  5]
 [26 31  8]
 [46 55 14]]
Covariance Matrix:
[[ 2.16666667 -1.96666667]
 [-1.96666667  5.36666667]]


## Q2: Based on NumPy Mathematics and Statistics

In [3]:

array = np.array([[1, -2, 3], [-4, 5, -6]])

# (i) Find element-wise absolute value
abs_array = np.abs(array)
print("Element-wise absolute value:")
print(abs_array)
print()

# (ii) Find the 25th, 50th, and 75th percentile of flattened array, for each column, for each row
flattened_array = array.flatten()
print("Percentiles of flattened array:")
print("25th percentile:", np.percentile(flattened_array, 25))
print("50th percentile:", np.percentile(flattened_array, 50))
print("75th percentile:", np.percentile(flattened_array, 75))
print()

print("Percentiles for each column:")
for col in range(array.shape[1]):
    col_array = array[:, col]
    print(f"Column {col}:")
    print("25th percentile:", np.percentile(col_array, 25))
    print("50th percentile:", np.percentile(col_array, 50))
    print("75th percentile:", np.percentile(col_array, 75))
    print()

print("Percentiles for each row:")
for row in range(array.shape[0]):
    row_array = array[row, :]
    print(f"Row {row}:")
    print("25th percentile:", np.percentile(row_array, 25))
    print("50th percentile:", np.percentile(row_array, 50))
    print("75th percentile:", np.percentile(row_array, 75))
    print()

# (iii) Mean, Median and Standard Deviation of flattened array, of each column, and each row
print("Mean, Median and Standard Deviation of flattened array:")
print("Mean:", np.mean(flattened_array))
print("Median:", np.median(flattened_array))
print("Standard Deviation:", np.std(flattened_array))
print()

print("Mean, Median and Standard Deviation for each column:")
for col in range(array.shape[1]):
    col_array = array[:, col]
    print(f"Column {col}:")
    print("Mean:", np.mean(col_array))
    print("Median:", np.median(col_array))
    print("Standard Deviation:", np.std(col_array))
    print()

print("Mean, Median and Standard Deviation for each row:")
for row in range(array.shape[0]):
    row_array = array[row, :]
    print(f"Row {row}:")
    print("Mean:", np.mean(row_array))
    print("Median:", np.median(row_array))
    print("Standard Deviation:", np.std(row_array))
    print()

# (b) For the array: a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0]). Find floor, ceiling and truncated value, rounded values
a = np.array([-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0])

print("Floor, Ceiling and Truncated values:")
print("Floor:", np.floor(a))
print("Ceiling:", np.ceil(a))
print("Truncated:", np.trunc(a))
print()

print("Rounded values:")
print("Round to nearest integer:", np.round(a))
print("Round to one decimal place:", np.round(a, 1))

Element-wise absolute value:
[[1 2 3]
 [4 5 6]]

Percentiles of flattened array:
25th percentile: -3.5
50th percentile: -0.5
75th percentile: 2.5

Percentiles for each column:
Column 0:
25th percentile: -2.75
50th percentile: -1.5
75th percentile: -0.25

Column 1:
25th percentile: -0.25
50th percentile: 1.5
75th percentile: 3.25

Column 2:
25th percentile: -3.75
50th percentile: -1.5
75th percentile: 0.75

Percentiles for each row:
Row 0:
25th percentile: -0.5
50th percentile: 1.0
75th percentile: 2.0

Row 1:
25th percentile: -5.0
50th percentile: -4.0
75th percentile: 0.5

Mean, Median and Standard Deviation of flattened array:
Mean: -0.5
Median: -0.5
Standard Deviation: 3.8622100754188224

Mean, Median and Standard Deviation for each column:
Column 0:
Mean: -1.5
Median: -1.5
Standard Deviation: 2.5

Column 1:
Mean: 1.5
Median: 1.5
Standard Deviation: 3.5

Column 2:
Mean: -1.5
Median: -1.5
Standard Deviation: 4.5

Mean, Median and Standard Deviation for each row:
Row 0:
Mean: 0.666666

# Q3: Based on Searching and Sorting

In [6]:
sorted_array = np.array([10, 16, 16, 52, 54, 62, 453])
indices = np.argsort(array)

smallest_elements = sorted_array[:4]

largest_elements = sorted_array[-5:]

integer_elements = array[array.astype(int) == array]

float_elements = array[array.astype(int) != array]

print("Sorted array:", sorted_array)
print("Indices of sorted array:", indices)
print("Smallest elements:", smallest_elements)
print("Largest elements:", largest_elements)
print("Integer elements:", integer_elements)
print("Float elements:", float_elements)


Sorted array: [ 10  16  16  52  54  62 453]
Indices of sorted array: [[1 0 2]
 [2 0 1]]
Smallest elements: [10 16 16 52]
Largest elements: [ 16  52  54  62 453]
Integer elements: [ 1 -2  3 -4  5 -6]
Float elements: []
